# Generated by Django 4.1.7 on 2023-09-08 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conducteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('numero_permis', models.CharField(max_length=20, unique=True)),
                ('date_expiration_permis', models.DateField()),
                ('numero_telephone', models.CharField(max_length=15)),
                ('adresse_email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=100)),
                ('modele', models.CharField(max_length=100)),
                ('annee_fabrication', models.IntegerField()),
                ('vin', models.CharField(max_length=17, unique=True)),
                ('type_carburant', models.CharField(max_length=50)),
                ('numero_plaque', models.CharField(max_length=15, unique=True)),
                ('statut', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('conducteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_parc.conducteur')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_parc.vehicule')),
            ],
        ),
        migrations.CreateModel(
            name='Localisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('date_localisation', models.DateTimeField()),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_parc.vehicule')),
            ],
        ),
        migrations.CreateModel(
            name='Kilometrage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_record', models.DateField()),
                ('kilometrage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_parc.vehicule')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriqueUtilisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_utilisation', models.DateField()),
                ('kilometrage_parcouru', models.DecimalField(decimal_places=2, max_digits=10)),
                ('conducteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_parc.conducteur')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_parc.vehicule')),
            ],
        ),
        migrations.CreateModel(
            name='Entretien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_entretien', models.CharField(max_length=100)),
                ('cout', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_entretien', models.DateField()),
                ('details_entretien', models.TextField()),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_parc.vehicule')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(max_length=100)),
                ('chemin_fichier', models.FileField(upload_to='documents/')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_parc.vehicule')),
            ],
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_depense', models.CharField(max_length=100)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_depense', models.DateField()),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_parc.vehicule')),
            ],
        ),
        migrations.CreateModel(
            name='Assurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compagnie_assurance', models.CharField(max_length=100)),
                ('numero_police', models.CharField(max_length=50, unique=True)),
                ('date_debut_assurance', models.DateField()),
                ('date_fin_assurance', models.DateField()),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_parc.vehicule')),
            ],
        ),
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_alerte', models.CharField(max_length=100)),
                ('date_alerte', models.DateField()),
                ('details_alerte', models.TextField()),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_parc.vehicule')),
            ],
        ),
    ]
